name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [[ $GITHUB_REF == "refs/heads/dev" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "EC2_HOST=${{ secrets.EC2_HOST_STAGING }}" >> $GITHUB_ENV
            echo "EC2_SSH_KEY='${{ secrets.EC2_SSH_KEY_STAGING }}'" >> $GITHUB_ENV
            echo "DEPLOY_PATH=prodstack-staging" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest-dev" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> $GITHUB_ENV
            echo "EC2_SSH_KEY='${{ secrets.EC2_SSH_KEY }}'" >> $GITHUB_ENV
            echo "DEPLOY_PATH=prodstack" >> $GITHUB_ENV
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prodstack-backend:${{ env.DOCKER_TAG }} ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/prodstack-backend:${{ env.DOCKER_TAG }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prodstack-frontend:${{ env.DOCKER_TAG }} ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/prodstack-frontend:${{ env.DOCKER_TAG }}

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ env.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ env.EC2_HOST }} << EOF
            cd ~/${{ env.DEPLOY_PATH }}
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/prodstack-backend:${{ env.DOCKER_TAG }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/prodstack-frontend:${{ env.DOCKER_TAG }}
            docker-compose up -d
          EOF
